### ISSUE TITLE
Form size changing may cause display problem

### ISSUE THREAD

**Issue by KevinZonda** [IntelOrca/teds-terminal#19]
Changing the form size may cause some problem:
![image](https://user-images.githubusercontent.com/33132228/109946016-b57ee980-7ccf-11eb-8d68-4b3f8d45edd5.png)

**Comment by IntelOrca** [comment]
Not sure if this is related to WinPTY or not. In any case, I will soon archive this repo as I deem it obsolete now that that Windows Terminal exists.

**Comment by KevinZonda** [comment]
Thank you, what a pity :(
